server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker_db
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true